version: '3'
services:
    solid:
        build:
            context: .
            dockerfile: ./docker/solid.Dockerfile
        ports:
            - 443:443
        volumes:
            - ./data/keys:/opt/solid/keys
            - ./data/db:/opt/solid/db
            - ./data/pods:/opt/solid/pods
    pubsub:
        build:
            context: https://github.com/pdsinterop/php-solid-pubsub-server.git#main
        ports:
            - 8080:8080
        expose:
            - 8080
        depends_on:
            - solid
    mailpit:
        image: axllent/mailpit
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        restart: unless-stopped
        ports:
            - 8025:8025
            - 2525:1025
        volumes:
            - ./data/mailpit-data:/data
