---
name: Solid Test Suites

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  solid-testsuite:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start Docker Containers
        run: |
          ./tests/testsuite/run-solid-test-suite.sh
