---
name: Solid Test Suites

env:
  # Docker Hub digest (i.e. hash) of the used Docker Images that do not have a version tag.
  PUBSUB_TAG: latest@sha256:b73a2a5c98d2005bb667dfc69d1c859d704366024298b9caa24ea2e182c456c2

on:
  push:
    branches:
      - workflow
  pull_request:
    branches: [ main ]
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  solid-testsuite:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Create docker tag from git reference
        # A tag name may only contain lower- and uppercase letters, digits, underscores, periods and dashes.
        run: |
          echo "TAG=$(echo -n "${{ github.ref_name }}" \
            | tr --complement --squeeze-repeats '[:alnum:]._-' '_')" \
            >> "${GITHUB_ENV}"

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache-solid-php-docker
        with:
          path: cache/solid-php
          key: solid-php-docker-${{ github.sha }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start Docker Containers
        run: |
          ./tests/testsuite/run-solid-test-suite.sh
